### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [skeeto/ulid-c#1]
Dear @skeeto,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows 7 x64 w/o C?

**Comment by skeeto** [comment]
Instead of that, here's a less direct but more general solution:

1. Download [w64devkit](https://github.com/skeeto/w64devkit), my Mingw-w64 distribution specifically designed to solve this problem. It's a single "portable" .zip file, no installers. Pre-built toolchains are under "Releases" on the right. It currently supports every Windows back to and including XP, which includes Windows 7.

2. Unzip `w64devkit-1.21.0.zip` (or whatever version you prefer) in some convenient location. Doesn't matter where.

3. Run `w64devkit.exe` to bring up a unix shell ([busybox-w32](https://frippery.org/busybox/)). It speaks native Windows paths, and there's no virtual unix root `/` like msys. Navigate to the ulid-c repository.

4. Run `make ulidgen` or perhaps more sensibly `make CFLAGS=-O LDFLAGS=-s ulidgen`. Now you have your `ulidgen.exe`, a native Windows console program.

5. If you don't want w64devkit anymore, close the terminal then simply delete the `w64devkit/` directory that you had unzipped. No uninstall required.

**Comment by sergeevabc** [comment]
Oh, Christopher, it's you, the author of Enchive! Oh, 6 years [passed](https://github.com/skeeto/enchive/issues/5).

Right, I managed to follow your instructions without hesitation, except for the ambiguity of how to “navigate to the repository”. In the end I downloaded your Github repository as ZIP by pressing the green button CODE and extracted it to %userprofile% where I was teleported after launching `w64devkit.exe` according to `ls` command.

`ulidgen.exe` was compiled without errors. Its UX leaves much to be desired (e.g. the check does not give a clear message about how it ended, the stamps are more computer-oriented than [human-oriented](https://github.com/oklog/ulid/issues/13#issuecomment-347358571), etc), but it works, indeed. Thank you.
